apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: agrosense
spec:
  storageClassName: standard  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: agrosense
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "agrosense-identity-api"
        metrics_path: /api/metrics/users
        static_configs:
          - targets: ["agrosense-api-gateway.agrosense.svc.cluster.local:80"]

      - job_name: "agrosense-sensor-ingestion-api"
        metrics_path: /api/metrics/sensors
        static_configs:
          - targets: ["agrosense-api-gateway.agrosense.svc.cluster.local:80"]

      - job_name: "agrosense-property-api"
        metrics_path: /api/metrics/properties
        static_configs:
          - targets: ["agrosense-api-gateway.agrosense.svc.cluster.local:80"]

      - job_name: "agrosense-alerts-api"
        metrics_path: /api/metrics/alerts
        static_configs:
          - targets: ["agrosense-api-gateway.agrosense.svc.cluster.local:80"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: agrosense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534  
      containers:
        - name: prometheus
          image: prom/prometheus:v3.2.1
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: agrosense
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090  # acesso via <ip-do-node>:30090
