apiVersion: v1
kind: Secret
metadata:
  name: agrosense-app-secret
  namespace: agrosense
type: Opaque
stringData:
  # banco de dados  
  ConnectionStrings__Identity: "Host=postgres-identity;Port=5432;Database=agrosense_identity;Username=agrosense;Password=agrosense"
  ConnectionStrings__Property: "Host=postgres-property;Port=5432;Database=agrosense_property;Username=agrosense;Password=agrosense"
  ConnectionStrings__Sensor: "Host=postgres-sensor-ingestion;Port=5432;Database=agrosense_sensor;Username=agrosense;Password=agrosense"
  ConnectionStrings__Alerts: "Host=postgres-alerts;Port=5432;Database=agrosense_alerts;Username=agrosense;Password=agrosense"
  
  # JWT
  Jwt__Secret: "USS36tsed91iXE1DQ9SyoOhHtJzEvvXoEi9x3aybuxU="
  Jwt__Issuer: "agrosense-identity"
  Jwt__Audience: "production"
  Jwt__ExpirationInMinutes: "15"